/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunityIndexRouteImport } from './routes/opportunity/index'
import { Route as FollowupIndexRouteImport } from './routes/followup/index'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as ContractIndexRouteImport } from './routes/contract/index'
import { Route as OpportunityIdRouteImport } from './routes/opportunity/$id'
import { Route as FollowupIdRouteImport } from './routes/followup/$id'
import { Route as CustomerIdRouteImport } from './routes/customer/$id'
import { Route as ContractIdRouteImport } from './routes/contract/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityIndexRoute = OpportunityIndexRouteImport.update({
  id: '/opportunity/',
  path: '/opportunity/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupIndexRoute = FollowupIndexRouteImport.update({
  id: '/followup/',
  path: '/followup/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractIndexRoute = ContractIndexRouteImport.update({
  id: '/contract/',
  path: '/contract/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityIdRoute = OpportunityIdRouteImport.update({
  id: '/opportunity/$id',
  path: '/opportunity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupIdRoute = FollowupIdRouteImport.update({
  id: '/followup/$id',
  path: '/followup/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIdRoute = CustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractIdRoute = ContractIdRouteImport.update({
  id: '/contract/$id',
  path: '/contract/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contract/$id': typeof ContractIdRoute
  '/customer/$id': typeof CustomerIdRoute
  '/followup/$id': typeof FollowupIdRoute
  '/opportunity/$id': typeof OpportunityIdRoute
  '/contract/': typeof ContractIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/followup/': typeof FollowupIndexRoute
  '/opportunity/': typeof OpportunityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contract/$id': typeof ContractIdRoute
  '/customer/$id': typeof CustomerIdRoute
  '/followup/$id': typeof FollowupIdRoute
  '/opportunity/$id': typeof OpportunityIdRoute
  '/contract': typeof ContractIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/followup': typeof FollowupIndexRoute
  '/opportunity': typeof OpportunityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contract/$id': typeof ContractIdRoute
  '/customer/$id': typeof CustomerIdRoute
  '/followup/$id': typeof FollowupIdRoute
  '/opportunity/$id': typeof OpportunityIdRoute
  '/contract/': typeof ContractIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/followup/': typeof FollowupIndexRoute
  '/opportunity/': typeof OpportunityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contract/$id'
    | '/customer/$id'
    | '/followup/$id'
    | '/opportunity/$id'
    | '/contract/'
    | '/customer/'
    | '/followup/'
    | '/opportunity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contract/$id'
    | '/customer/$id'
    | '/followup/$id'
    | '/opportunity/$id'
    | '/contract'
    | '/customer'
    | '/followup'
    | '/opportunity'
  id:
    | '__root__'
    | '/'
    | '/contract/$id'
    | '/customer/$id'
    | '/followup/$id'
    | '/opportunity/$id'
    | '/contract/'
    | '/customer/'
    | '/followup/'
    | '/opportunity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractIdRoute: typeof ContractIdRoute
  CustomerIdRoute: typeof CustomerIdRoute
  FollowupIdRoute: typeof FollowupIdRoute
  OpportunityIdRoute: typeof OpportunityIdRoute
  ContractIndexRoute: typeof ContractIndexRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  FollowupIndexRoute: typeof FollowupIndexRoute
  OpportunityIndexRoute: typeof OpportunityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/': {
      id: '/opportunity/'
      path: '/opportunity'
      fullPath: '/opportunity/'
      preLoaderRoute: typeof OpportunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followup/': {
      id: '/followup/'
      path: '/followup'
      fullPath: '/followup/'
      preLoaderRoute: typeof FollowupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/': {
      id: '/contract/'
      path: '/contract'
      fullPath: '/contract/'
      preLoaderRoute: typeof ContractIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$id': {
      id: '/opportunity/$id'
      path: '/opportunity/$id'
      fullPath: '/opportunity/$id'
      preLoaderRoute: typeof OpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followup/$id': {
      id: '/followup/$id'
      path: '/followup/$id'
      fullPath: '/followup/$id'
      preLoaderRoute: typeof FollowupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$id': {
      id: '/customer/$id'
      path: '/customer/$id'
      fullPath: '/customer/$id'
      preLoaderRoute: typeof CustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/$id': {
      id: '/contract/$id'
      path: '/contract/$id'
      fullPath: '/contract/$id'
      preLoaderRoute: typeof ContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractIdRoute: ContractIdRoute,
  CustomerIdRoute: CustomerIdRoute,
  FollowupIdRoute: FollowupIdRoute,
  OpportunityIdRoute: OpportunityIdRoute,
  ContractIndexRoute: ContractIndexRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  FollowupIndexRoute: FollowupIndexRoute,
  OpportunityIndexRoute: OpportunityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
